/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef calculadora_CONSTANTS_H
#define calculadora_CONSTANTS_H

#include "calculadora_types.h"

namespace calculadora {

class calculadoraConstants {
 public:
  calculadoraConstants();

};

extern const calculadoraConstants g_calculadora_constants;

} // namespace

#endif
