/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "calculadora_constants.h"

namespace calculadora {

const calculadoraConstants g_calculadora_constants;

calculadoraConstants::calculadoraConstants() {
}

} // namespace

