/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "cliente.h"
#include <math.h>

int *
sum_1_svc(parametros arg1,  struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	 	result = arg1.param_1 + arg1.param_2;

	return &result;
}

int *
mul_1_svc(parametros arg1,  struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	 result = arg1.param_1 * arg1.param_2;

	return &result;
}

double *
div_1_svc(parametros arg1,  struct svc_req *rqstp)
{
	static double  result;

	/*
	 * insert server code here
	 */
	 result = (double) arg1.param_1 / (double) arg1.param_2;

	return &result;
}

int *
res_1_svc(parametros arg1,  struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	 result = arg1.param_1 - arg1.param_2;

	return &result;
}

int *
raiz_1_svc(parametro arg1,  struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */
	 result = sqrt(arg1);

	return &result;
}

int *
exp_1_svc(parametro arg1,  struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}

int *
sumvec_1_svc(parametros_vec arg1,  struct svc_req *rqstp)
{
	static int  result;

	/*
	 * insert server code here
	 */

	return &result;
}
