/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "cliente.h"


void
sumprog_1(char *host, parametros sum_1_arg1)
{
	CLIENT *clnt;
	int  *result_1;

#ifndef	DEBUG
	clnt = clnt_create (host, SUMPROG, SUMPROGSERVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = sum_1(sum_1_arg1, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("%d + %d = %d\n", sum_1_arg1.param_1, sum_1_arg1.param_2, *result_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
mulprog_1(char *host, parametros mul_1_arg1)
{
	CLIENT *clnt;
	int  *result_1;

#ifndef	DEBUG
	clnt = clnt_create (host, MULPROG, MULPROGSERVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = mul_1(mul_1_arg1, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("%d * %d = %d\n", mul_1_arg1.param_1, mul_1_arg1.param_2, *result_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
divprog_1(char *host, parametros div_1_arg1)
{
	CLIENT *clnt;
	double  *result_1;

#ifndef	DEBUG
	clnt = clnt_create (host, DIVPROG, DIVPROGSERVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = div_1(div_1_arg1, clnt);
	if (result_1 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("%d / %d = %f\n", div_1_arg1.param_1, div_1_arg1.param_2, (*result_1));
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
resprog_1(char *host, parametros res_1_arg1)
{
	CLIENT *clnt;
	int  *result_1;

#ifndef	DEBUG
	clnt = clnt_create (host, RESPROG, RESPROGSERVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = res_1(res_1_arg1, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("%d - %d = %d\n", res_1_arg1.param_1, res_1_arg1.param_2, *result_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
raizprog_1(char *host, parametro raiz_1_arg1)
{
	CLIENT *clnt;
	int  *result_1;

#ifndef	DEBUG
	clnt = clnt_create (host, RAIZPROG, RAIZPROGSERVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = raiz_1(raiz_1_arg1, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}

	printf("%sqrt(%d) = %f\n", raiz_1_arg1, *result_1);
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
expprog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	parametro exp_1_arg1;

#ifndef	DEBUG
	clnt = clnt_create (host, EXPPROG, EXPPROGSERVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = exp_1(exp_1_arg1, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
sumvecprog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	parametros_vec sumvec_1_arg1;

#ifndef	DEBUG
	clnt = clnt_create (host, SUMVECPROG, SUMVECPROGSERVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = sumvec_1(sumvec_1_arg1, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 3) {
		printf ("usage: %s server_host operation params*\n", argv[0]);
		exit (1);
	}else{

		host = argv[1];

		if(!strcmp(argv[2], "sum")){
			if(argc < 5){
				fprintf(stderr, "%s necesita dos parámetros", argv[2]);
				exit(1);
			}
			parametros params;
			params.param_1 = atoi(argv[3]);
			params.param_2 = atoi(argv[4]);

			sumprog_1(host, params);
		}

		if(!strcmp(argv[2], "mul")){
			if(argc < 5){
				fprintf(stderr, "%s necesita dos parámetros", argv[2]);
				exit(1);
			}
			parametros params;
			params.param_1 = atoi(argv[3]);
			params.param_2 = atoi(argv[4]);

			mulprog_1(host, params);
		}

		if(!strcmp(argv[2], "div")){
			if(argc < 5){
				fprintf(stderr, "%s necesita dos parámetros", argv[2]);
				exit(1);
			}
			parametros params;
			params.param_1 = atoi(argv[3]);
			params.param_2 = atoi(argv[4]);

			divprog_1(host, params);
		}

		if(!strcmp(argv[2], "res")){
			if(argc < 5){
				fprintf(stderr, "%s necesita dos parámetros", argv[2]);
				exit(1);
			}
			parametros params;
			params.param_1 = atoi(argv[3]);
			params.param_2 = atoi(argv[4]);

			resprog_1(host, params);
		}

		if(!strcmp(argv[2], "raiz")){
			if(argc < 4){
				fprintf(stderr, "%s necesita un parámetros", argv[2]);
				exit(1);
			}
			int param = atoi(argv[3]);
			raizprog_1(host, param);
		}

		if(!strcmp(argv[2], "exp")){

		}

		if(!strcmp(argv[2], "sumvec")){
			if(argc < 5){
				fprintf(stderr, "%s necesita dos parámetros", argv[2]);
				exit(1);
			}
		}
	}

	expprog_1 (host);
	sumvecprog_1 (host);
exit (0);
}
