/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CLIENTE_H_RPCGEN
#define _CLIENTE_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct parametros {
	int param_1;
	int param_2;
};
typedef struct parametros parametros;

struct parametros_vec {
	int *param_1;
	int *param_2;
};
typedef struct parametros_vec parametros_vec;

typedef int parametro;

#define SUMPROG 0x20000001
#define SUMPROGSERVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUM 1
extern  int * sum_1(parametros , CLIENT *);
extern  int * sum_1_svc(parametros , struct svc_req *);
extern int sumprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUM 1
extern  int * sum_1();
extern  int * sum_1_svc();
extern int sumprog_1_freeresult ();
#endif /* K&R C */

#define MULPROG 0x20000002
#define MULPROGSERVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define MUL 1
extern  int * mul_1(parametros , CLIENT *);
extern  int * mul_1_svc(parametros , struct svc_req *);
extern int mulprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define MUL 1
extern  int * mul_1();
extern  int * mul_1_svc();
extern int mulprog_1_freeresult ();
#endif /* K&R C */

#define DIVPROG 0x20000003
#define DIVPROGSERVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define DIV 1
extern  double * div_1(parametros , CLIENT *);
extern  double * div_1_svc(parametros , struct svc_req *);
extern int divprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define DIV 1
extern  double * div_1();
extern  double * div_1_svc();
extern int divprog_1_freeresult ();
#endif /* K&R C */

#define RESPROG 0x20000004
#define RESPROGSERVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define RES 1
extern  int * res_1(parametros , CLIENT *);
extern  int * res_1_svc(parametros , struct svc_req *);
extern int resprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define RES 1
extern  int * res_1();
extern  int * res_1_svc();
extern int resprog_1_freeresult ();
#endif /* K&R C */

#define RAIZPROG 0x20000005
#define RAIZPROGSERVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define RAIZ 1
extern  int * raiz_1(parametro , CLIENT *);
extern  int * raiz_1_svc(parametro , struct svc_req *);
extern int raizprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define RAIZ 1
extern  int * raiz_1();
extern  int * raiz_1_svc();
extern int raizprog_1_freeresult ();
#endif /* K&R C */

#define EXPPROG 0x20000006
#define EXPPROGSERVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define EXP 1
extern  int * exp_1(parametro , CLIENT *);
extern  int * exp_1_svc(parametro , struct svc_req *);
extern int expprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define EXP 1
extern  int * exp_1();
extern  int * exp_1_svc();
extern int expprog_1_freeresult ();
#endif /* K&R C */

#define SUMVECPROG 0x20000007
#define SUMVECPROGSERVER 1

#if defined(__STDC__) || defined(__cplusplus)
#define SUMVEC 1
extern  int * sumvec_1(parametros_vec , CLIENT *);
extern  int * sumvec_1_svc(parametros_vec , struct svc_req *);
extern int sumvecprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define SUMVEC 1
extern  int * sumvec_1();
extern  int * sumvec_1_svc();
extern int sumvecprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_parametros (XDR *, parametros*);
extern  bool_t xdr_parametros_vec (XDR *, parametros_vec*);
extern  bool_t xdr_parametro (XDR *, parametro*);

#else /* K&R C */
extern bool_t xdr_parametros ();
extern bool_t xdr_parametros_vec ();
extern bool_t xdr_parametro ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CLIENTE_H_RPCGEN */
