/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "cliente.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static int *
_sum_1 (parametros  *argp, struct svc_req *rqstp)
{
	return (sum_1_svc(*argp, rqstp));
}

static int *
_mul_1 (parametros  *argp, struct svc_req *rqstp)
{
	return (mul_1_svc(*argp, rqstp));
}

static double *
_div_1 (parametros  *argp, struct svc_req *rqstp)
{
	return (div_1_svc(*argp, rqstp));
}

static int *
_res_1 (parametros  *argp, struct svc_req *rqstp)
{
	return (res_1_svc(*argp, rqstp));
}

static int *
_raiz_1 (parametro  *argp, struct svc_req *rqstp)
{
	return (raiz_1_svc(*argp, rqstp));
}

static int *
_exp_1 (parametro  *argp, struct svc_req *rqstp)
{
	return (exp_1_svc(*argp, rqstp));
}

static int *
_sumvec_1 (parametros_vec  *argp, struct svc_req *rqstp)
{
	return (sumvec_1_svc(*argp, rqstp));
}

static void
sumprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		parametros sum_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SUM:
		_xdr_argument = (xdrproc_t) xdr_parametros;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _sum_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
mulprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		parametros mul_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case MUL:
		_xdr_argument = (xdrproc_t) xdr_parametros;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _mul_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
divprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		parametros div_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case DIV:
		_xdr_argument = (xdrproc_t) xdr_parametros;
		_xdr_result = (xdrproc_t) xdr_double;
		local = (char *(*)(char *, struct svc_req *)) _div_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
resprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		parametros res_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case RES:
		_xdr_argument = (xdrproc_t) xdr_parametros;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _res_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
raizprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		parametro raiz_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case RAIZ:
		_xdr_argument = (xdrproc_t) xdr_parametro;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _raiz_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
expprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		parametro exp_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case EXP:
		_xdr_argument = (xdrproc_t) xdr_parametro;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _exp_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

static void
sumvecprog_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		parametros_vec sumvec_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case SUMVEC:
		_xdr_argument = (xdrproc_t) xdr_parametros_vec;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) _sumvec_1;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (SUMPROG, SUMPROGSERVER);
	pmap_unset (MULPROG, MULPROGSERVER);
	pmap_unset (DIVPROG, DIVPROGSERVER);
	pmap_unset (RESPROG, RESPROGSERVER);
	pmap_unset (RAIZPROG, RAIZPROGSERVER);
	pmap_unset (EXPPROG, EXPPROGSERVER);
	pmap_unset (SUMVECPROG, SUMVECPROGSERVER);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, SUMPROG, SUMPROGSERVER, sumprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (SUMPROG, SUMPROGSERVER, udp).");
		exit(1);
	}
	if (!svc_register(transp, MULPROG, MULPROGSERVER, mulprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (MULPROG, MULPROGSERVER, udp).");
		exit(1);
	}
	if (!svc_register(transp, DIVPROG, DIVPROGSERVER, divprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (DIVPROG, DIVPROGSERVER, udp).");
		exit(1);
	}
	if (!svc_register(transp, RESPROG, RESPROGSERVER, resprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (RESPROG, RESPROGSERVER, udp).");
		exit(1);
	}
	if (!svc_register(transp, RAIZPROG, RAIZPROGSERVER, raizprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (RAIZPROG, RAIZPROGSERVER, udp).");
		exit(1);
	}
	if (!svc_register(transp, EXPPROG, EXPPROGSERVER, expprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (EXPPROG, EXPPROGSERVER, udp).");
		exit(1);
	}
	if (!svc_register(transp, SUMVECPROG, SUMVECPROGSERVER, sumvecprog_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (SUMVECPROG, SUMVECPROGSERVER, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, SUMPROG, SUMPROGSERVER, sumprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (SUMPROG, SUMPROGSERVER, tcp).");
		exit(1);
	}
	if (!svc_register(transp, MULPROG, MULPROGSERVER, mulprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (MULPROG, MULPROGSERVER, tcp).");
		exit(1);
	}
	if (!svc_register(transp, DIVPROG, DIVPROGSERVER, divprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (DIVPROG, DIVPROGSERVER, tcp).");
		exit(1);
	}
	if (!svc_register(transp, RESPROG, RESPROGSERVER, resprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (RESPROG, RESPROGSERVER, tcp).");
		exit(1);
	}
	if (!svc_register(transp, RAIZPROG, RAIZPROGSERVER, raizprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (RAIZPROG, RAIZPROGSERVER, tcp).");
		exit(1);
	}
	if (!svc_register(transp, EXPPROG, EXPPROGSERVER, expprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (EXPPROG, EXPPROGSERVER, tcp).");
		exit(1);
	}
	if (!svc_register(transp, SUMVECPROG, SUMVECPROGSERVER, sumvecprog_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (SUMVECPROG, SUMVECPROGSERVER, tcp).");
		exit(1);
	}

	svc_run ();
	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}
