/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "cliente.h"


void
sumprog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	parametros sum_1_arg1;

#ifndef	DEBUG
	clnt = clnt_create (host, SUMPROG, SUMPROGSERVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = sum_1(sum_1_arg1, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
mulprog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	parametros mul_1_arg1;

#ifndef	DEBUG
	clnt = clnt_create (host, MULPROG, MULPROGSERVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = mul_1(mul_1_arg1, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
divprog_1(char *host)
{
	CLIENT *clnt;
	double  *result_1;
	parametros div_1_arg1;

#ifndef	DEBUG
	clnt = clnt_create (host, DIVPROG, DIVPROGSERVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = div_1(div_1_arg1, clnt);
	if (result_1 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
resprog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	parametros res_1_arg1;

#ifndef	DEBUG
	clnt = clnt_create (host, RESPROG, RESPROGSERVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = res_1(res_1_arg1, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
raizprog_1(char *host)
{
	CLIENT *clnt;
	double  *result_1;
	parametro raiz_1_arg1;

#ifndef	DEBUG
	clnt = clnt_create (host, RAIZPROG, RAIZPROGSERVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = raiz_1(raiz_1_arg1, clnt);
	if (result_1 == (double *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
expprog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	parametro exp_1_arg1;

#ifndef	DEBUG
	clnt = clnt_create (host, EXPPROG, EXPPROGSERVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = exp_1(exp_1_arg1, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


void
sumvecprog_1(char *host)
{
	CLIENT *clnt;
	int  *result_1;
	parametros_vec sumvec_1_arg1;

#ifndef	DEBUG
	clnt = clnt_create (host, SUMVECPROG, SUMVECPROGSERVER, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	result_1 = sumvec_1(sumvec_1_arg1, clnt);
	if (result_1 == (int *) NULL) {
		clnt_perror (clnt, "call failed");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 2) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	sumprog_1 (host);
	mulprog_1 (host);
	divprog_1 (host);
	resprog_1 (host);
	raizprog_1 (host);
	expprog_1 (host);
	sumvecprog_1 (host);
exit (0);
}
