/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "cliente.h"

bool_t
xdr_parametros (XDR *xdrs, parametros *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->param_1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->param_2))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_parametros_vec (XDR *xdrs, parametros_vec *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)&objp->param_1, sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	 if (!xdr_pointer (xdrs, (char **)&objp->param_2, sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_parametro (XDR *xdrs, parametro *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, objp))
		 return FALSE;
	return TRUE;
}
